# Pandas

#### 1) How do you read a CSV file into a Pandas DataFrame? Provide an example. (code)

In [5]:
import numpy as np
import pandas as pd

In [9]:
data = pd.read_csv("fifa_data.csv")
data.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

#### 2) How can you select specific columns from a DataFrame? (code)

In [19]:
# suppose we want to select Name and Age column from this dataset:
specific_col = data[["Name", "Age"]]
specific_col

                     Name  Age
0                L. Messi   31
1       Cristiano Ronaldo   33
2               Neymar Jr   26
3                  De Gea   27
4            K. De Bruyne   27
...                   ...  ...
18202        J. Lundstram   19
18203  N. Christoffersson   19
18204           B. Worman   16
18205      D. Walker-Rice   17
18206           G. Nugent   16

[18207 rows x 2 columns]

#### 3) How do you filter rows of a DataFrame based on a condition? (code)

In [33]:
# Suppose I want that the data where the "Nationality" is "Argentina" and age is greater than or equal to 30
conditional_rows = data[(data['Nationality'] == "Argentina") & (data['Age'] >= 30)]
conditional_rows.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
23,23,153079,S. Agüero,30,https://cdn.sofifa.org/players/4/19/153079.png,Argentina,https://cdn.sofifa.org/flags/52.png,89,89,Manchester City,...,90.0,30.0,20.0,12.0,13.0,15.0,6.0,11.0,14.0,€119.3M
38,38,167664,G. Higuaín,30,https://cdn.sofifa.org/players/4/19/167664.png,Argentina,https://cdn.sofifa.org/flags/52.png,88,88,Milan,...,86.0,35.0,22.0,18.0,5.0,12.0,7.0,5.0,10.0,NaN
89,89,192366,N. Otamendi,30,https://cdn.sofifa.org/players/4/19/192366.png,Argentina,https://cdn.sofifa.org/flags/52.png,85,85,Manchester City,...,80.0,83.0,85.0,84.0,12.0,5.0,8.0,11.0,12.0,€52.7M
138,138,183898,A. Di María,30,https://cdn.sofifa.org/players/4/19/183898.png,Argentina,https://cdn.sofifa.org/flags/52.png,84,84,Paris Saint-Germain,...,82.0,35.0,59.0,56.0,10.0,7.0,11.0,12.0,11.0,€54.6M

#### 4) How can you group data in a DataFrame by a specific column and apply an aggregate function? (code)

In [45]:
# here I am showing all the other colums for nationality with count() aggregate function
grouped_data = data.groupby('Nationality').count() 
# now only age with the average
grouped_data = data.groupby('Nationality')[['Age']].mean() 
grouped_data

                   Age
Nationality
Afghanistan  22.500000
Albania      24.025000
Algeria      27.050000
Andorra      28.000000
Angola       25.866667
...                ...
Uzbekistan   29.500000
Venezuela    24.313433
Wales        24.736434
Zambia       22.222222
Zimbabwe     26.846154

[164 rows x 1 columns]

#### 5) Explain how to merge two DataFrames on a common column. (code)

In [61]:
#for this I am creating two dataframe for the existing dataset
data1 = data[['Name', 'Age', 'Nationality']]
data2 = data[['Club', 'Overall', 'Release Clause','Age']]

# I am doing left join for this
after_merged = pd.merge(data1, data2, how="left", on="Age")
after_merged.head()

       Name  Age Nationality                 Club  Overall Release Clause
0  L. Messi   31   Argentina         FC Barcelona       94        €226.5M
1  L. Messi   31   Argentina         FC Barcelona       91          €164M
2  L. Messi   31   Argentina  Paris Saint-Germain       89          €111M
3  L. Messi   31   Argentina    Tottenham Hotspur       88         €66.6M
4  L. Messi   31   Argentina          Real Madrid       87         €62.5M

#### 6) How do you handle missing values in a DataFrame? (code)

In [93]:
data.isnull().sum()

Unnamed: 0           0
ID                   0
Name                 0
Age                  0
Photo                0
                  ...
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 89, dtype: int64

In [101]:
# As football player ratings is a sensitive thing, so we can not fill those values, like Gk rating, Messi has 6.0 skill 
#rating but De Gea has 90, so we can not fill this value, so removing the cols will be efficient
data.dropna(axis= 1)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club Logo,Value,Wage,Special
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,https://cdn.sofifa.org/teams/2/light/241.png,€110.5M,€565K,2202
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,https://cdn.sofifa.org/teams/2/light/45.png,€77M,€405K,2228
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,https://cdn.sofifa.org/teams/2/light/73.png,€118.5M,€290K,2143
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,https://cdn.sofifa.org/teams/2/light/11.png,€72M,€260K,1471
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,https://cdn.sofifa.org/teams/2/light/10.png,€102M,€355K,2281
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,https://cdn.sofifa.org/teams/2/light/121.png,€60K,€1K,1307
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,https://cdn.sofifa.org/teams/2/light/703.png,€60K,€1K,1098
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,https://cdn.sofifa.org/teams/2/light/1944.png,€60K,€1K,1189
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,https://cdn.sofifa.org/teams/2/light/15048.png,€60K,€1K,1228
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,https://cdn.sofifa.org/teams/2/light/15048.png,€60K,€1K,1321

#### 8) What is the difference between iloc and loc in Pandas? (theory + code)

In [123]:
data1.loc[0:2, 'Name':'Age']

                Name  Age
0           L. Messi   31
1  Cristiano Ronaldo   33
2          Neymar Jr   26

In [125]:
data1.iloc[2]

Name           Neymar Jr
Age                   26
Nationality       Brazil
Name: 2, dtype: object

#### 10) How do you save a DataFrame to a CSV file? (code)

In [127]:
data.to_csv('innovative_pandas.csv', index=False)

# Text Preprocessing

#### 4) How do you handle punctuation in text preprocessing? Provide a Python example. (theory + code)

In [132]:
import re
sample = "My name is, Tabib. I'm a good-boy. What's you opinion."

cleaned_sen = re.sub(r'[^\w\s]', '', sample)
cleaned_sen

'My name is Tabib Im a goodboy Whats you opinion'

#### 7)How can you remove numeric values from a text in Python? Provide an example. (code)

In [141]:
import re

text = "My name is, Tabib. My number is 017xxxxxxx"

cleaned_text = re.sub(r'\d+', '', text)  # \d+ matches one or more digits
cleaned_text

'My name is, Tabib. My number is xxxxxxx'

#### 8) What is the purpose of normalization in text preprocessing? Give an example. (theory + code)

In [153]:
import re

# Sample text
text = "I can't believe this! I love natural language processing for sentiment analysis, isn't it?"

# Normalization function
def normalize_text(text):
    # Lowercase the text
    text = text.lower()
    
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    # Expand contractions (optional, just a simple example)
    contractions = {"can't": "cannot", "it's": "it is", "isn't": "is not"}
    for contraction, full_form in contractions.items():
        text = text.replace(contraction, full_form)
    
    return text

# Normalize the text
normalized_text = normalize_text(text)
print("Normalized Text:", normalized_text)

Normalized Text: i cant believe this i love natural language processing for sentiment analysis isnt it

# Text Vectorization:

#### 4) Describe how you can create a TF-IDF representation of a text corpus using Python. (code)

In [144]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "My name is Tabib",
    "I am a student of DIU",
    "I love natural language processing for sentiment analysis"
]

# Initialize the TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(corpus)

# Convert the TF-IDF matrix to an array and get feature names (terms)
tfidf_array = tfidf_matrix.toarray()
terms = vectorizer.get_feature_names_out()

# Print TF-IDF array and corresponding terms
print("TF-IDF Matrix:")
print(tfidf_array)
print("\nFeature Names (Terms):")
print(terms)

TF-IDF Matrix:
[[0.         0.         0.         0.         0.5        0.
  0.         0.5        0.5        0.         0.         0.
  0.         0.         0.5       ]
 [0.5        0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.5        0.
  0.         0.5        0.        ]
 [0.         0.37796447 0.         0.37796447 0.         0.37796447
  0.37796447 0.         0.         0.37796447 0.         0.37796447
  0.37796447 0.         0.        ]]

Feature Names (Terms):
['am' 'analysis' 'diu' 'for' 'is' 'language' 'love' 'my' 'name' 'natural'
 'of' 'processing' 'sentiment' 'student' 'tabib']